src/Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FunApp.Services.DataServices;
using FunApp.Services.Models.Category;
using FunApp.Services.Models.Joke;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace FunApp.Web.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoriesService _categoriesService;

        private readonly IJokesService _jokesService;

        public CategoryController(ICategoriesService categoriesService, IJokesService jokesService)
        {
            _categoriesService = categoriesService;
            _jokesService = jokesService;
        }

        public IActionResult Index(int? page)
        {
            var categories = _categoriesService.GetAllViewModels();
            
            var nextPage = page ?? 1;

            var pagetCategories = categories.ToPagedList(nextPage, 10);

            var model = new AllCategoriesViewModel
            {
                Categories = pagetCategories
            };

            return View(model);
        }

        public IActionResult Details(int id, string name, int? page)
        {
            var jokes = _jokesService.ByCategory<DetailsViewModel>(id);

            var nextPage = page ?? 1;

            var pagedJokes = jokes.ToPagedList(nextPage, 4);

            var model = new JokesByCategoryDetailsViewModel
            {
                Name = name,
                Jokes = pagedJokes
            };

            return View(model);
        }
    }
}

src/Web/Controllers/JokeController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using FunApp.Services.DataServices;
using FunApp.Services.MachineLearning;
using FunApp.Services.Models.Joke;
using FunApp.Web.Models.Joke;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FunApp.Web.Controllers
{
    public class JokeController : BaseController
    {
        private readonly IJokesService _jokesService;
        private readonly ICategoriesService _categoriesService;
        private readonly IJokesCategorizer _jokesCategorizer;

        public JokeController(IJokesService jokesService, ICategoriesService categoriesService, IJokesCategorizer jokesCategorizer)
        {
            _jokesService = jokesService;
            _categoriesService = categoriesService;
            _jokesCategorizer = jokesCategorizer;
        }

        [Authorize]
        public IActionResult Create()
        {
            ViewData["Categories"] = _categoriesService.GetAll()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NameAndCount
                });
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateJokeInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var id = await _jokesService.Create(input.CategoryId, input.Content);

            return RedirectToAction("Details", new {id = id});
        }

        public IActionResult Details(int id)
        {
            var detailsViewModel = _jokesService.ById<DetailsViewModel>(id);

            return View(detailsViewModel);
        }

        public IActionResult Edit(int id)
        {
            var jokeViewModel = _jokesService.ById<JokeViewModel>(id);
            ViewData["Categories"] = _categoriesService.GetAll()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NameAndCount
                });

            return View(jokeViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(JokeViewModel model)
        {

            var id = await _jokesService.Edit(model);

            return RedirectToAction("Details", new { id = id });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await _jokesService.Delete(id);
            if (!deleted)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public SuggestCategoryResult SuggestCategory(string joke)
        {
            var category = _jokesCategorizer.Categorize("MlModels/JokesCategoryModel.zip", joke);
            var categoryId = _categoriesService.GetCategoryId(category);
            return new SuggestCategoryResult{CategoryId = categoryId ?? 0, CategoryName = category};
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FunApp.Web</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FunApp.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Joke" asp-action="Create">Create</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FunApp.Web</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>